# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      id-token: write # Enable GitHub OIDC token issuance

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: |
        cd src
        cd net10
        dotnet restore
    - name: Build
      run: |
        cd src
        cd net10
        dotnet build --no-restore
    - name: Test
      run: |
        cd src 
        cd net10    
        cd MCPArrayTests
        # dotnet test --no-build --verbosity normal

    - name: Pack MCP_PDF
      run: |
        cd src
        cd net10
        cd MCPArray       
        dotnet pack --configuration Release --output ../nupkg

    - name: Upload NuGet package artifact
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v4
      with:
        name: MCPArray2Any 
        path: src/net10/nupkg/*.nupkg
        retention-days: 1
        
    - name: NuGet login (OIDC â†’ temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: ignatandreiyahoo 
        token-service-url: https://int.nugettest.org/api/v2/token
        
    - name: push to nuget
      #if: startsWith(github.ref, 'refs/tags/v') # This line ensures the step runs only if a tag version is present
      run: |
        cd src
        cd net10
        cd nupkg
        # dotnet nuget push "*.nupkg" --api-key  ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
        dotnet nuget push "*.nupkg" --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://apiint.nugettest.org/v3/index.json
